version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: playground
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
